// chat
export const SUBMIT_MESSAGE = 'SEND_MESSAGE'
export const RECEIVING_MESSAGE = 'RECEIVE_MESSAGE'
export const SENDING_MESSAGE = 'SENDING_MESSAGE'
export const TYPING_MESSAGE = 'TYPING_MESSAGE'
